spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
  token-validity-in-seconds: 3600